-- MySQL Script generated by MySQL Workbench
-- Sun Dec 29 17:13:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`project` (
  `id` INT NOT NULL,
  `pname` VARCHAR(255) NOT NULL,
  `photo` DECIMAL(10,2) NULL,
  `readmore` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idname_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

USE `db` ;

-- -----------------------------------------------------
-- Placeholder table for view `db`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `db`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`view1`;
USE `db`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
